services:
  app:
    build: .
    container_name: everdownload-container
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis:6379
      - REDIS_PASSWORD=
      - PORT=8080
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: everdownload-redis
    ports:
      - "6379:6379"
    restart: unless-stopped
